apiVersion: v1
kind: Service
metadata:
  name: netdisk_production
  namespace: production
spec:
  selector:
    app: netdisk_production
  ports:
  - name: http
    targetPort: 8888
    port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdisk_production
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdisk_production
  template:
    metadata:
      labels:
        app: netdisk_production
    spec:
      containers:
      - name: netdisk_production
        image: registry.cn-hangzhou.aliyuncs.com/876500/netdisk:${build_tag}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "python3 main.py"]
        ports:
        - name: http
          containerPort: 8888
        env:
        - name: branch
          value: <BRANCH_NAME>